name: 构建与发布镜像

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 0 点
  workflow_dispatch:
    inputs:
      push_to_registry:
        description: '是否推送到 GitHub Packages (ghcr.io)'
        type: boolean
        default: false
        required: false
      qqwry_url:
        description: '可选：自定义 qqwry.dat 下载地址（构建阶段）'
        type: string
        required: false
        default: ''

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  test:
    name: 单元测试
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设置 Go 版本
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: go mod tidy 校验（保持依赖可复现）
        run: |
          go mod tidy
          git diff --exit-code || (echo 'go mod tidy 产生变更，请提交' && exit 1)
      - name: 构建自检
        run: go build .
      - name: 运行测试
        run: go test ./... -cover
  build:
    name: 构建并发布镜像
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'schedule' || github.event.inputs.push_to_registry == 'true'
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设置 Buildx
        uses: docker/setup-buildx-action@v3
      - name: 计算镜像名称（统一转小写）
        id: meta
        shell: bash
        run: |
          echo "image=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
      - name: 登录 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 生成构建标签
        id: vars
        shell: bash
        run: |
          DATE=$(date +%Y%m%d)
          echo "date=$DATE" >> $GITHUB_OUTPUT
      - name: 构建并推送（自定义数据源）
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.qqwry_url != ''
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            QQWRY_URL=${{ github.event.inputs.qqwry_url }}
          tags: |
            ${{ steps.meta.outputs.image }}:latest
            ${{ steps.meta.outputs.image }}:${{ steps.vars.outputs.date }}
            ${{ steps.meta.outputs.image }}:${{ github.sha }}
      - name: 构建并推送（默认数据源）
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.qqwry_url == ''
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.image }}:latest
            ${{ steps.meta.outputs.image }}:${{ steps.vars.outputs.date }}
            ${{ steps.meta.outputs.image }}:${{ github.sha }}
